### ISSUE TITLE
Bug:  wlapp shows reconcile true when not having the WebSphere Liberty Operator

### ISSUE THREAD

**Issue by tam512** [WASdev/websphere-liberty-operator#126]
This problem is seen on Azure AKS cluster

I installed WebSphere Liberty Operator (WLO) in operators namespace on AKS cluster.  Then I uninstalled the WLO by removing the subscription and its csv.  Check to make sure there is no wlo-controller-manager pod in operators namespace.  
```
$ oc get all -n operators
No resources found in operators namespace.
```
Then I try to  deploy sample daytrader7 app with WebSphereLibertyApplication kind, and expect to see reconciled is false, but I see the reconcile is true.  There is no application pod or any resource created
```
$ oc get wlapp -n dt-ns1
NAME         IMAGE                                                                                                    EXPOSED   RECONCILED   AGE
daytrader7   hyc-wassvt-team-image-registry-docker-local.artifactory.swg-devops.com/daytrader/sample-daytrader7:db2   true                   16s

$ oc get all -n dt-ns1
No resources found in dt-ns1 namespace.
```

**Comment by leochr** [comment]
@tam512 In the output above, the `Reconciled` column doesn't state `true`. It's empty, meaning that the WebSphereLibertyApplication CR is not processed - because the operator is not watching the CR. It's working as expected.

Wondering whether you looked at the value for `Exposed` column, which states true.

**Comment by leochr** [comment]
Closing as it's working as expected
