### ISSUE TITLE
Operator README

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#30]
The [README](https://github.com/WASdev/websphere-liberty-operator/blob/main/config/manifests/description.md) for the operator must contain the following information.

Template Fields:

- Name: Product Name
- Introduction: Paragraph overview of the workload
- Details: Describes what the workload is deploying
- Prerequisites: Describes Environmental pre-requisites
- SecurityContextConstraints Requirements: Describe the SecurityContextConstraints pre-requisite
- Resources Required: Describes Minimum System Resources Required
- Installing: Ways to install
- Configuration: Define the Parms/Configuration Option
- Storage: Define how workload storage setup
- Limitations: Define key limitations

-------

Use [WebSphere Automation README](https://github.ibm.com/websphere/automation-operator/blob/main/config/manifests/description.md) as an example/reference

Additional information:
[Operator README](https://playbook.cloudpaklab.ibm.com/cm/cluster-service-version-design-requirements/#Operator_README)

**Comment by leochr** [comment]
@mcurran-us It seems the CASE also requires this. If you already have a skeleton with some information, please point us to it. Thanks

**Comment by mcurran-us** [comment]
@leochr Here's what I have so far:  https://github.ibm.com/websphere/liberty-case-bundle/blob/main/stable/ibm-websphere-liberty-bundle/case/ibm-websphere-liberty/README.md
Please let me know of any corrections or additions.  There are a couple of sections where I just have the default text because I wasn't sure what to put for those sections.
