### ISSUE TITLE
Run and validate FVT tests on OCP 4.12 GA/early driver

### ISSUE THREAD

**Issue by leochr** [WASdev/websphere-liberty-operator#348]
The automated cluster provisioning in pipeline supports pre-release drivers of OCP. Run the WLO build with an OCP 4.12 pre-release driver and ensure that FVT tests (e2e tests) pass. Investigate any failures.

**Comment by leochr** [comment]
@davco01a could you please point to/provide info on how pre-release OCP driver can be used via WLO pipeline? Thanks.

**Comment by leochr** [comment]
@yongja79 OCP 4.12 has GA’ed. I don’t yet see it in Fyre. But the cluster provisioner in OnePipeline may already have access to it. Dave Cohen or Chris Webster might know. If that's the case, you could submit a build by setting build param `ocp_version`. If it's not yet available and we have to request it via the pre-release support in 1P then configure the build params `pre-release`, `pre-release-ocp-url`, `pre-release-rhcos-url`. Thanks.

**Comment by yongja79** [comment]
I've currently run the tests on a local 4.12 cluster and after some changes to the semeru tests (not due to any 4.12 changes) they all pass. There is an issue with running them in the onepipeline automation due to the version of rook ceph storage class we try to install that no longer works with a 4.12 cluster

**Comment by yongja79** [comment]
Updates made to the onepipeline scripts to get the Rook Ceph and to the kuttl test timeouts. All the kuttl tests now pass on OCP 4.12
